language: python
sudo: false
cache:
- pip
- apt
python:
- '3.6'
addons:
  apt:
    packages:
    - python3-enchant
    - aspell-en
    - aspell-de
install:
- pip install -U codecov
- pip install -r requirements-dev.txt
script:
- coverage run --source="pytest_translations" -m "pytest"
after_success:
- codecov
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: bXxLJ3dcm3JPKOAbsF+cvClNuRNGNv2eKzhHrtbHOdPfvLnVk5V2i1F3bUv4GR1TPdYkvPWlJJCPWCEx9CfFkhWCV9usgB0+c4H1q0QumXfYmkHJ5vqGImozQBTq80YIDaW+V7575Me0Hev2v4LaulHcJ88xfqvgrlngxjZtPU4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Thermondo/pytest-translations
