language: python
sudo: false
cache:
 - pip
 - apt
python:
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - python-enchant
    - python3-enchant
    - aspell-en
    - aspell-de
install:
  - pip install -U pip
  - pip install -r requirements-dev.txt
  - pip install -U coveralls
script:
  - coverage run --source="pytest_translations.py" -m "pytest"
after_success:
  - coveralls
