name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        pytest-version: [
          "pytest>=6.1,<6.2",
          "pytest>=6.2,<6.3"
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip downloads
        uses: syphar/restore-pip-download-cache@v1

      - name: Install system package dependencies
        run: |
          sudo apt-get install -y python3-enchant aspell-en aspell-de

      - name: installing python dependencies
        run: |
          pip install -U codecov
          pip install -r requirements-dev.txt

      - name: installing ${{ matrix.pytest-version }}
        run: |
          pip install "${{ matrix.pytest-version }}"

      - name: running tests
        run: coverage run --source="pytest_translations" -m "pytest"

      - name: uploading coverage
        run: codecov --required
